INSERT INTO plants (
    plant_name,
    seed_type,
    exp_yield,
    blend,
    min_height,
    max_height,
    cbd_content,
    thc_content,
    climate,
    medical_usage,
    genes,
    supplier,
    flowering_time_min,
    flowering_time_max,
    planting_date,
    soil_brand,
    soil_npk,
  )
VALUES (
    'crystal',
    'Feminized'
    400,
    'Indica Dominant: 60% Indica / 40% Sativa',
    100,
    180,
    '<1%',
    '19%',
    'Temperate, Warm, Cool',
    'Nausea, Pain, Stress',
    'White Widow x Northern Lights',
    'MSNL UK',
    8,
    10,
    '2022-08-04',
    'Fox Farm Ocean Forest',
    '0.30, 0.45, 0.05',
  );)