INSERT INTO plants (
    plant_name,
    seed_type,
    exp_yield,
    blend,
    min_height,
    max_height,
    cbd_content,
    thc_content,
    climate,
    medical_usage,
    genes,
    supplier,
    flowering_time_min,
    flowering_time_max,
    planting_date,
    soil_brand,
    soil_npk,
  )
VALUES (
    'starwberry cough',
    'Feminized'
    400,
    'Sativa',
    180,
    220,
    '<1%',
    '24%',
    'Warm',
    'Anxiety, PTSD, Stress',
    'Strawberry Fields x Haze',
    'MSNL UK',
    8,
    10,
    '2022-08-04',
    'Fox Farm Ocean Forest',
    '0.30, 0.45, 0.05',
  );)