INSERT INTO plants (
    plant_name,
    seed_type,
    exp_yield,
    blend,
    min_height,
    max_height,
    cbd_content,
    thc_content,
    climate,
    medical_usage,
    genes,
    supplier,
    flowering_time_min,
    flowering_time_max,
    planting_date,
    soil_brand,
    soil_npk,
  )
VALUES (
    'sunset sherbet',
    'Feminized'
    350,
    'Indica Dominant: 85% Indica / 15% Sativa',
    100,
    180,
    '<1%',
    '25%',
    'Warm',
    'Anxiety, Depression, PTSD, Stress',
    'Girl Scout Cookies x Pink Panties',
    'MSNL UK',
    8,
    10,
    '2022-08-04',
    'Fox Farm Ocean Forest',
    '0.30, 0.45, 0.05',
  );)